---
- name: Create app directory
  file: path={{ app_path }} state=directory  
    
- name: Download app
  get_url:
    url: https://github.com/mahnve/go-web/releases/download/{{ app_version }}/run 
    dest: "{{ app_path }}/app"
    mode: 0755    
  notify: restart app    

- name: symlink
  file: src={{ app_path }} dest={{ app_link }} state=link

- name: upload supervisord template    
  template: src=supervisord.template dest=/etc/supervisor/conf.d/app.conf      
  notify: restart app

- name: load app
  supervisorctl: name=app state=present
